### ISSUE TITLE
.env path

### ISSUE THREAD

**Issue by portothree** [buddy-works/buddy-cli#10]
I'm using a webpack plugin which try to find env vars in './.env' but I'm getting the error "Failed to load ./.env.".
I have added the correct variables to the pipeline/project in project options.

Its possible to change the path for the .env file in the plugin configuration, so where does buddy stores the .env with the vars I have defined in the project options?

**Comment by mical** [comment]
Is this the problem with buddy-cli, or you have general problem with pipeline variables and webpack ? If the later you should contact support@buddy.works with links to your pipeline / project. 

If it is indeed problem with buddy-cli please be more specific. buddy-cli is reading environmental variables from system not from specific .env file. Im closing for now, if you elaborate i'll reopen.
