### ISSUE TITLE
Idea: Project Status

### ISSUE THREAD

**Issue by gisu** [buddy-works/buddy-cli#2]
Personally I would find it quite good if one could ask about the CLI the status. So which project is in progress, which is failed.

Would be a real help as a terminal user.

**Comment by mical** [comment]
Status in project has different meaning. It can be active or closed.
You can always however list all pipelines in project - there is displayed status of last execution.
`buddy-cli pl ls`

**Comment by YoulittledevilYou** [comment]
What is this for?

**Comment by Kivlov84** [comment]
@gisu we have added your request to our backlog - we'll let you know once this feature is added.

**Comment by mical** [comment]
in backlog but wont be done anytime soon
