### ISSUE TITLE
Security Vulnerability in Dependency

### ISSUE THREAD

**Issue by James-Bovis** [buddy-works/buddy-cli#3]
Hi, I got a notice from GitHub that one of my dependencies had a security vulnerability and should be upgraded. Namely, it is the "hoek" dependency which buddy-cli uses in their tree.

Here is my tree from using `npm ls hoek`

```
buddyworks-cli@1.0.8
│ └─┬ request@2.81.0
│   └─┬ hawk@3.1.3
│     ├─┬ boom@2.10.1
│     │ └── hoek@2.16.3  deduped
│     ├── hoek@2.16.3
│     └─┬ sntp@1.0.9
│       └── hoek@2.16.3  deduped
```

GutHub reccomends uograding to v4.2.1 and above.Hopefully it's something that can be looked into and perhaps sorted.

**Comment by mical** [comment]
dependencies updated
